#pragma once
#include "I18nKeys.h"

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.
// clang-format off

namespace i18n_strings {

extern const char STRINGS_EN_DATA[];
extern const uint16_t OFFSETS_EN[];
extern const char STRINGS_ZH_CN_DATA[];
extern const uint16_t OFFSETS_ZH_CN[];

}  // namespace i18n_strings
